package com.rotaract.project.domain.enumeration;

public enum AreaOfInteresEnum {
    //PEACE_CONFLICT_RESOLUTION, DISEASE_PREVENTION, WATER_SANITATION, MATERNAL_CHILD_HEALTH, BASIC_EDUCATION, ECONOMIC_COMMUNITY

    PEACE_CONFLICT_RESOLUTION,
    DISEASE_PREVENTION,
    WATER_SANITATION,
    MATERNAL_CHILD_HEALTH,
    BASIC_EDUCATION,
    ECONOMIC_COMMUNITY,
    GENERAL_AREAS,
    COMMUNITY,
    INTERNATIONAL,
    PROFESSIONAL,
    NEW_GENERATIONS,
    FUNDING_EVENT,
    POLIO,
    ENVIRONMENT,
    CATASTROPHIES_RESPONSE,
    CLUB_SERVICE
}
