package com.rotaract.project.domain.enumeration;

public enum AreaOfInteresEnum {
    PEACE_CONFLICT_RESOLUTION, DISEASE_PREVENTION, WATER_SANITATION, MATERNAL_CHILD_HEALTH, BASIC_EDUCATION, ECONOMIC_COMMUNITY
}
