package com.rotaract.project.domain.enumeration;

/**
 * The ProfessionalAreaEnum enumeration.
 */
public enum ProfessionalAreaEnum {
    LEGAL, FINANCE, ENGINEERING, QUALITY_ASSURANCE, REAL_STATE, PURCHASING, MEDIA_COMMUNICATIONS, ACCOUTING,
    BUSINESS_DEVELOPMENT, PRODUCT_MANAGMENT, EDUCATION, ENTREPRENEURSHIP, ENVIROMENTAL_SCIENCES,
    PROGRAM_PRODUCT_MANAGEMENT, RESEARCH, MARKETING, OPERATIONS, HUMAN_RESOURCES, HEALTHCARE_SERVCES,
    MILITARY_PROTECTIVE_SERVICES, COMMUNITY_SOCIAL_SERVICES, SUPPORT, INFORMATION_TECHNOLOGY, SALES, OTHER
}
